import uuid
from typing import Optional

from sqlalchemy import Enum, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base, TimestampMixin, UUIDPKMixin
from app.models.enums import WorkerStatus


class WorkerStoreNumberSequence(UUIDPKMixin, Base):
    """
    One row per site. Holds the last-issued store number for that site.

    Store numbers are generated by SELECT ... FOR UPDATE on this row inside
    the same DB transaction that inserts the new worker, which serializes
    concurrent registrations and guarantees no two workers at a site ever
    receive the same number - even under simultaneous requests.
    """

    __tablename__ = "worker_store_number_sequences"

    site_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sites.id"), nullable=False, unique=True, index=True
    )
    last_number: Mapped[int] = mapped_column(Integer, default=0, nullable=False)


class Worker(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "workers"

    site_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("sites.id"), nullable=False, index=True)
    department_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("departments.id"), nullable=True
    )

    # Permanent identifier, e.g. "0001". Zero-padded, sequential, never reused,
    # unique within a site (a worker's one active site for the MVP).
    store_number: Mapped[str] = mapped_column(String(16), nullable=False, index=True)

    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    national_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    phone_number: Mapped[str] = mapped_column(String(32), nullable=False, index=True)

    job_role: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    supervisor: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    employment_status: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    status: Mapped[WorkerStatus] = mapped_column(
        Enum(WorkerStatus, native_enum=False, values_callable=lambda e: [x.value for x in e]),
        default=WorkerStatus.ACTIVE,
        nullable=False,
    )

    site: Mapped["Site"] = relationship(back_populates="workers")

    __table_args__ = (
        UniqueConstraint("site_id", "store_number", name="uq_worker_site_store_number"),
        # A National ID should not be re-registered at the same site.
        UniqueConstraint("site_id", "national_id", name="uq_worker_site_national_id"),
    )
